site_name: Digital Forensic Recipes
site_url: https://www.dfrecipes.fr/
site_author: Prantice
site_description: Having troubles with digital forensic ? We've got you covered !
repo_url: https://github.com/Praentice/praentice.github.io
repo_name: Praentice/praentice.github.io

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs

plugins:
  - social:
      cards_dir: assets/images/social
      cards_font: Roboto
      cards_color:
        fill: "#273746" 
        text: "#FFFFFF"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Praentice
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/Prantice
    - icon: fontawesome/solid/globe
      link: https://www.youtube.com/watch?v=oHg5SJYRHA0
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
    copyright: >
      Copyright &copy; 2022 Prantice –
      <a href="#__consent">Change cookie settings</a>
